services:
  web:
    build: web
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - mongodb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/adventuretube
    networks:
      - adventuretube-network
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      - adventuretube-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - adventuretube-network
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=adventuretube
    networks:
      - adventuretube-network
volumes:
  data: { }
networks:
 adventuretube-network: